services:
  client:
    build:
      context: ../../
      dockerfile: apps/web/docker/development/Dockerfile
    depends_on:
      - database
    networks:
      - app_network
    ports:
      - 3000:3000
    volumes:
      - ../../apps/web:/app/apps/web:delegated

  database:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    build:
      context: ../../
      dockerfile: apps/api/docker/development/Dockerfile
    depends_on:
      - database
    networks:
      - app_network
    ports:
      - 3333:3333
    volumes:
      - ../../apps/server:/app/apps/server:delegated

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
