services:
  web:
    build:
      context: ../../
      dockerfile: apps/web/docker/production/Dockerfile
    depends_on:
      - database
    networks:
      - app_network
    ports:
      - 3000:3000

  database:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: ../../
      dockerfile: apps/api/docker/production/Dockerfile
    depends_on:
      - database
    networks:
      - app_network
    ports:
      - 3333:3333

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
